refactor: 💡 SDWebImageSwiftUI Research
SAP/cloud-sdk-ios-cai pull request #32
Opened 2021-08-09 09:18 UTC by ShadowTourist

`SDWebImageSwiftUI` research, comments anytime.

2021-08-09 09:30 UTC, ShadowTourist commented
|before|after|
|-|-|
|<img width="438" alt="Screen Shot 2021-08-09 at 4 59 59 PM" src="https://user-images.githubusercontent.com/33440079/128685668-2f426e79-6fcc-4565-96f2-5e2b558f7766.png">|<img width="438" alt="Screen Shot 2021-08-09 at 5 05 22 PM" src="https://user-images.githubusercontent.com/33440079/128685689-b07a2638-385c-413b-842a-9bbd98439390.png">|

2021-08-09 09:53 UTC, ShadowTourist commented
Important: `Note: However, many differences behavior between iOS 13/14's is hard to fixup. Due to maintain issue, in the future release, we will drop the iOS 13 supports and always match SwiftUI 2.0's behavior.`

2021-09-01 23:11 UTC, MarcoEidinger requested changes
Overall looks really good! 

I noticed that cache has a certain impact on memory. Lets add a section to the README to inform the app developer that app developer decides if/when image cache gets deleted. For example, for `onDisappear` for `AssistantView` the following is possible

```Swift
SDImageCache.shared.clearMemory()
SDImageCache.shared.clearDisk()
```

Also the README file has to be updated in the following areas
- https://github.com/SAP/cloud-sdk-ios-cai#dependencies
- https://github.com/SAP/cloud-sdk-ios-cai#image-related

2021-09-01 23:11 UTC, MarcoEidinger commented on Sources/SAPCAI/UI/Common/SwiftUI/AvatarView.swift
> +            Image(systemName: "icloud.slash")
is this new?

2021-09-01 23:11 UTC, MarcoEidinger commented on Sources/SAPCAI/UI/Common/UIKit/ImageViewWrapper.swift
> +struct ImageViewWrapper<Content>: View where Content: View {
Please add a Preview for `ImageViewWrapper`

2021-09-01 23:11 UTC, MarcoEidinger commented on Sources/SAPCAI/UI/Common/UIKit/ImageViewWrapper.swift
> +        /// retry strategy missed
what does this comment mean?

2021-09-02 22:11 UTC, MarcoEidinger requested changes
Thank yo so much @ShadowTourist , that looks really great!!

@justinguo I assume that is also fine from your side?

Here is my last-minute nit-picking feedback. Once incorporated I will merge the PR into a new branch `devBreaking`.

Just in case you or Justin wonder why a new branch: there are already changes in dev branch which were not yet published. I might want to roll those out as a patch release but the gif support through SDWebImage is a minor/major release worth due to the breaking changes of switching package dependencies.

2021-09-02 22:55 UTC, justinguo commented
Overall looks good to me. I tested and it works fine on device.

2021-09-02 23:01 UTC, justinguo commented
@ShadowTourist Did you add the retry operation in `updateUIView()` method? Like if display failure view, can user tap the image again to retry the downloading and decoding?

2021-09-03 01:26 UTC, ShadowTourist commented
> @ShadowTourist Did you add the retry operation in `updateUIView()` method? Like if display failure view, can user tap the image again to retry the downloading and decoding?

No, currently image view has no capability of interaction, so retry can be added by `SDWebImage`, there is a option called `SDWebImageRetryFailed` for image load failed. If we need add this for `ImageViewWrapper`?

2021-09-03 20:27 UTC, MarcoEidinger approved these changes

2021-09-03 20:28 UTC, merged